version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: facebook-clone-prod
    restart: unless-stopped
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    volumes:
      - ./data:/mysql